modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"
[[mods]]
modId="cc"
version="${file.jarVersion}"
displayName="Claim Chunk"
displayURL="https://www.curseforge.com/minecraft/mc-mods/claim-chunk"
logoFile="logo.png"
credits="Modeling by welpstudent"
authors="Lupicus, MacTso"
description='''Claim Chunk'''
[[dependencies.cc]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
