modLoader="javafml"
loaderVersion="[53,)"
license="MIT License"
[[mods]]
modId="cc"
version="${file.jarVersion}"
displayName="Claim Chunk"
displayURL="https://www.curseforge.com/minecraft/mc-mods/claim-chunk"
logoFile="logo.png"
credits="Modeling by welpstudent"
authors="Lupicus, MacTso"
description='''Claim Chunk'''
[[dependencies.cc]]
    modId="forge"
    mandatory=true
    versionRange="[53,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.3,1.22)"
    ordering="NONE"
    side="BOTH"
